// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelTracker.Models;

namespace TravelTracker.Migrations
{
    [DbContext(typeof(TravelTrackerContext))]
    [Migration("20200806220926_clubmember")]
    partial class clubmember
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelTracker.Models.Club", b =>
                {
                    b.Property<int>("ClubId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ClubId");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("TravelTracker.Models.ClubMember", b =>
                {
                    b.Property<int>("ClubMemberId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClubId");

                    b.Property<int>("TravellerId");

                    b.HasKey("ClubMemberId");

                    b.HasIndex("ClubId");

                    b.HasIndex("TravellerId");

                    b.ToTable("ClubMember");
                });

            modelBuilder.Entity("TravelTracker.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityName");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("TravelTracker.Models.Traveller", b =>
                {
                    b.Property<int>("TravellerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("TravellerId");

                    b.ToTable("Travellers");
                });

            modelBuilder.Entity("TravelTracker.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClubId");

                    b.Property<int>("DestinationId");

                    b.Property<DateTime>("EndDate");

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("TravellerId");

                    b.HasKey("TripId");

                    b.HasIndex("ClubId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("TravellerId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("TravelTracker.Models.ClubMember", b =>
                {
                    b.HasOne("TravelTracker.Models.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelTracker.Models.Traveller", "Traveller")
                        .WithMany()
                        .HasForeignKey("TravellerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TravelTracker.Models.Trip", b =>
                {
                    b.HasOne("TravelTracker.Models.Club", "Club")
                        .WithMany("Trips")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelTracker.Models.Destination", "Destination")
                        .WithMany("Trips")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TravelTracker.Models.Traveller", "Traveller")
                        .WithMany("Trips")
                        .HasForeignKey("TravellerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
